name: C/C++ CI
   
on:
  workflow_dispatch:
  
permissions:
   contents: write
  


jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: [Hello.cpp, Hello2.cpp, Hello3.cpp]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest

    - name: Verify GCC Installation
      run: |
        gcc --version
        g++ --version

    - name: Run program
      run: g++ ${{ matrix.filename }}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: a.out

    - name: Configure git to use GitHub Actions token
      run: |
          git config --local user.email "ruzannaman2002@gmail.com"
          git config --local user.name "Ruzanna"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
