name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest

    - name: Verify GCC Installation
      run: |
        gcc --version
        g++ --version

    - name: Run program
      run: g++ Hello.cpp
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: a.out
    - uses: actions/checkout@v2
    - name: Create Tag
      run: |
        git config --local user.email "ruzannaman2002@gmail.com"
        git config --local user.name "Ruzanna"
        git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
        git push origin "v${{ github.run_number }}"
