name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest

    - name: Verify GCC Installation
      run: |
        gcc --version
        g++ --version

    - name: Run program
      run: g++ Hello.cpp
