name: C/C++ CI

permissions:
   contents: write
   
on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest

    - name: Verify GCC Installation
      run: |
        gcc --version
        g++ --version

    - name: Run program
      run: g++ Hello.cpp
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: a.out

    - name: Configure git to use GitHub Actions token
      run: |
          git config --local user.email "ruzannaman2002@gmail.com"
          git config --local user.name "Ruzanna"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    - name: Create Tag
      id: create_tag
      run: |
        git tag v${{ steps.git_short_hash.outputs.hash }}
        git push origin v${{ steps.git_short_hash.outputs.hash }}

    - name: 'Get Previous tag'
      id: previous_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
     
    - name: Release        
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
